// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.

#pragma once

UENUM(BlueprintType)
enum class EAdvancedSteamErrorCode : uint8
{
	UNKNOWN,
	ADVANCED_STEAM_MODULE_NOT_INITIALIZED,
	STEAM_NOT_INITIALIZED,
	STEAM_STATS_INVALID,
	STEAM_STATS_STORE_FAILED,
	VALUE_NOT_EXIST,
	UNSUPPORTED_TYPE,
	INVALID_GAMEID,
	INVALID_PLAYER_ID,
	INVALID_PLAYER_STATE,
	FILE_NOT_FOUND,
	FAILED_TO_SAVE_REPLAY,
	EXTERAL_WEBUI_OPEN_FAILED,
	FAILED_TO_WRITE_FILE,
	FAILED_TO_READ_FILE,
	FAILED_TO_SAVE_FILE,
	FAILED_TO_DELETE_FILE,
};
